export const APP_TEXTS = {
  common: {
    appName: 'Kabinett',
    subtitle: 'Biblioteca Virtual',
    allDocuments: 'Todos los documentos',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    error: 'Ha ocurrido un error inesperado',
    areYouSure: '¿Estás seguro?',
    close: 'Cerrar',
    closeIcon: '✕',
    selectPlaceholder: '-- Seleccionar --',
    discard: 'Descartar',
    upload: 'Subir',
    uploadAll: 'Subir Todos',
    confirmBackendIdError: 'No se puede confirmar: el item no tiene backendId asignado aún.',
    title: 'Título',
    composer: 'Compositor',
    customFieldsLabel: 'Campos personalizados',
    customFieldExample: 'Ej: {fieldName}',
  },
  sidebar: {
    collectionsTitle: 'Colecciones',
    newCollectionBtn: '+ Nueva',
    customFieldsBtn: '⚙️ Campos Personalizados',
    userManagementBtn: '👥 Gestión de Usuarios',
    deleteCollectionTooltip: 'Eliminar colección',
    allDocumentsIcon: '📚',
    collectionIcon: '📁',
    deleteIcon: '🗑️',
    profile: {
      currentRoleLabel: 'Rol actual',
      unknownRole: 'Desconocido',
      logoutTitle: 'Cerrar sesión',
      logoutBtn: 'Salir',
      logoutIcon: '🚪',
    },
  },
  modals: {
    confirmModal: {
      dangerIcon: '⚠️',
      infoIcon: '❓',
    },
    deleteCollection: {
      title: 'Eliminar Colección',
      message: '¿Estás seguro de que quieres eliminar esta colección? Las partituras guardadas en ella no se borrarán.',
      confirmBtn: 'Eliminar',
    },
    createCollection: {
      title: 'Crear Colección Virtual',
      namePlaceholder: 'Nombre de la colección',
      createBtn: 'Crear',
    },
    customFields: {
      title: 'Gestionar Campos Personalizados',
      activeFieldsLabel: 'Campos Activos',
      activeFieldsCount: 'Campos Activos ({count})',
      deleteFieldTooltip: 'Eliminar campo',
      createNewFieldLabel: 'Crear Nuevo Campo',
      fieldNameLabel: 'Nombre del Campo',
      fieldNamePlaceholder: 'Ej: Año de Composición, Editorial...',
      fieldTypeLabel: 'Tipo de Dato',
      fieldTypeOptions: {
        text: 'Texto',
        number: 'Número',
        select: 'Desplegable (Selección)',
        boolean: 'Verdadero / Falso',
      },
      optionsLabel: 'Opciones (separadas por coma)',
      optionsPlaceholder: 'Opción 1, Opción 2, Opción 3',
      closeBtn: 'Cerrar',
      saveFieldBtn: 'Guardar Campo',
    },
    editMetadata: {
      titlePrefix: 'Revisar Metadatos:',
      titleLabel: 'Título de la Obra',
      composerLabel: 'Compositor / Autor',
      tagsLabel: 'Etiquetas (#Tags)',
      customFieldsLabel: 'Campos Personalizados',
      cancelBtn: 'Cancelar',
      confirmBtn: 'Confirmar y Guardar Metadatos',
    },
  },
  upload: {
    dropzone: {
      sheetMusicIcon: '🎼',
      instruction: 'Arrastra tus partituras aquí o haz clic para explorar',
    },
    queue: {
      containerTitle: 'Cola de procesamiento y carga ({count})',
      containerIcon: '📥',
      uploadAllIcon: '🚀',
      fileIcon: '📄',
      pendingStatus: 'En espera',
      uploadSingleIcon: '⬆️',
      uploadSingleBtn: 'Subir',
      discardTooltip: 'Descartar',
      error: {
        icon: '⚠️',
        title: 'Error al procesar la partitura',
        defaultMessage: 'No se pudo leer el archivo o el PDF no contiene texto procesable.',
        discardBtn: 'Descartar',
      },
      metadataReview: {
        icon: '✨',
        title: 'Metadatos extraídos por IA/OCR',
        hint: 'Verifica antes de catalogar',
        titleLabel: 'Título de la Obra',
        titlePlaceholder: 'Título',
        composerLabel: 'Compositor / Autor',
        composerPlaceholder: 'Compositor',
        tagsLabel: 'Etiquetas (#Tags)',
        tagsPlaceholder: 'Añadir etiqueta y presionar Enter...',
        customFieldsLabel: 'Campos personalizados',
        confirmBtn: 'Confirmar y Añadir a Biblioteca',
      },
    },
  },
  tagInput: {
    placeholderEmpty: 'Escribe una etiqueta y pulsa Enter...',
    placeholderAdd: '+ Añadir...',
    tagPrefix: '#',
    existingLabel: 'Existente',
  },
  searchBar: {
    icon: '🔍',
    placeholder: 'Buscar por compositor, título, etiquetas o texto interno del PDF...',
    filtering: 'Filtrando...',
  },
  documentCard: {
    fileIcon: '📄',
    confirmedBadge: 'Confirmado',
    composerLabel: 'Compositor:',
    removeFromCollectionTooltip: 'Quitar de esta colección',
    removeFromCollectionBtn: '✕ Desasignar',
    viewPdfTooltip: 'Ver partitura en el visor integrado',
    viewPdfIcon: '👁️',
    viewPdfBtn: 'Ver PDF',
    editBtn: 'Editar',
    moveToOption: '📁 Mover a...',
  },
  pdfViewer: {
    sheetMusicIcon: '🎼',
    prevPageTitle: 'Página Anterior (←)',
    prevPageIcon: '◀',
    nextPageTitle: 'Página Siguiente (→)',
    nextPageIcon: '▶',
    pageSeparator: '/',
    zoomOut: '-',
    zoomIn: '+',
    fitWidthBtn: 'Ajustar Ancho',
    atrilIcon: '📖',
    atrilBtn: 'Modo Atril',
    atrilTitle: 'Activar Modo Atril (Pantalla completa)',
    closeBtn: '✕ Cerrar',
    exitAtrilBtn: '✕ Salir de Modo Atril',
    exitAtrilTitle: 'Salir de Modo Atril (Esc)',
    loadingText: 'Cargando partitura...',
    errorIcon: '⚠️',
    loadPdfErrorText: 'No se pudo cargar el archivo PDF.',
    loadPdfErrorLog: 'Error al cargar el PDF:',
    renderErrorLog: 'Error al renderizar página:',
  },
  facetedFilters: {
    titleIcon: '🎛️',
    title: 'Filtros Facetados',
    clearAllBtn: 'Limpiar todo',
    composersSection: 'Compositores / Autores',
    tagsSection: 'Etiquetas (#Tags)',
    customFieldsSection: 'Campos Personalizados',
    selectAllCustomField: 'Todos ({fieldName})',
    filterByCustomFieldPlaceholder: 'Filtrar por {fieldName}...',
  },
  home: {
    dropRejectedError: 'Formato no soportado en esta versión',
    rootLibraryTitle: 'Biblioteca Raíz',
    collectionTitlePrefix: 'Colección: ',
  },
  theme: {
    label: 'Apariencia',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
  },
  meta: {
    title: 'Kabinett',
    description: 'Biblioteca Virtual',
  },
  login: {
    title: 'Iniciar Sesión',
    usernameLabel: 'Usuario',
    passwordLabel: 'Contraseña',
    submitBtn: 'Entrar',
    submittingBtn: 'Iniciando sesión...',
    usernamePlaceholder: 'admin@kabinett.com',
    passwordPlaceholder: '••••••••',
    invalidCredentialsError: 'Usuario o contraseña incorrectos',
    invalidSessionResponseError: 'Respuesta de sesión inválida',
    genericError: 'Error al iniciar sesión',
  },
  auth: {
    loadingSession: 'Cargando sesión...',
    sessionExpired: 'Sesión expirada o no autorizada. Por favor, vuelve a iniciar sesión.',
    errors: {
      useAuthOutsideProvider: 'useAuth debe usarse dentro de un AuthProvider',
    },
  },
  adminUsers: {
    pageTitle: 'Gestión de Usuarios',
    pageSubtitle: 'Administra accesos, roles y cuentas activas en la plataforma.',
    backToDashboard: '← Volver al Panel Principal',
    newUserBtn: '+ Nuevo Usuario',
    searchPlaceholder: 'Buscar por nombre o correo...',
    allRolesOption: 'Todos los Roles',
    table: {
      headers: {
        name: 'Nombre',
        email: 'Email',
        role: 'Rol',
        status: 'Estado',
        actions: 'Acciones',
      },
      status: {
        active: 'Activo',
        inactive: 'Inactivo',
      },
      actions: {
        edit: 'Editar',
        activate: 'Activar',
        deactivate: 'Desactivar',
      },
      loading: 'Cargando usuarios...',
      empty: 'No se encontraron usuarios.',
    },
    pagination: {
      previous: 'Anterior',
      next: 'Siguiente',
      pageLabel: 'Página',
    },
    accessDeniedTitle: '403 - Acceso Denegado',
    accessDeniedMessage: 'No tienes permisos de Administrador para ver este panel.',
    backToHome: 'Volver al inicio',
    defaultLoadError: 'Error al cargar el listado de usuarios',
    defaultToggleError: 'No se pudo cambiar el estado del usuario',
    modal: {
      createTitle: 'Crear Nuevo Usuario',
      editTitle: 'Editar Usuario',
      nameLabel: 'Nombre Completo',
      namePlaceholder: 'Ej: Juan Pérez',
      emailLabel: 'Correo Electrónico',
      emailPlaceholder: 'ejemplo@kabinett.com',
      passwordLabel: 'Contraseña',
      passwordPlaceholderCreate: '••••••••',
      passwordPlaceholderEdit: '•••••••• (Dejar en blanco para conservar actual)',
      roleLabel: 'Rol asignado',
      activeStatusLabel: 'Usuario Activo',
      saveBtn: 'Guardar Usuario',
      savingBtn: 'Guardando...',
      cancelBtn: 'Cancelar',
    },
    alertModal: {
      defaultTitle: 'Acción No Permitida',
      subtitle: 'Atención',
      understandBtn: 'Entendido',
    },
  },
} as const;