export const APP_TEXTS = {
  common: {
    appName: 'Kabinett',
    subtitle: 'Biblioteca Virtual',
    allDocuments: 'Todos los documentos',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    error: 'Ha ocurrido un error inesperado',
    areYouSure: '¿Estás seguro?',
    close: 'Cerrar',
    closeIcon: '✕',
    selectPlaceholder: '-- Seleccionar --',
    discard: 'Descartar',
    upload: 'Subir',
    uploadAll: 'Subir Todos',
    confirmBackendIdError: 'No se puede confirmar: el item no tiene backendId asignado aún.',
    title: 'Título',
    composer: 'Compositor',
    customFieldsLabel: 'Campos personalizados',
    customFieldExample: 'Ej: {fieldName}',
  },
  sidebar: {
    collectionsTitle: 'Colecciones',
    newCollectionBtn: '+ Nueva',
    customFieldsBtn: '⚙️ Campos Personalizados',
    deleteCollectionTooltip: 'Eliminar colección',
    allDocumentsIcon: '📚',
    collectionIcon: '📁',
    deleteIcon: '🗑️',
  },
  modals: {
    confirmModal: {
      dangerIcon: '⚠️',
      infoIcon: '❓',
    },
    deleteCollection: {
      title: 'Eliminar Colección',
      message: '¿Estás seguro de que quieres eliminar esta colección? Las partituras guardadas en ella no se borrarán.',
      confirmBtn: 'Eliminar',
    },
    createCollection: {
      title: 'Crear Colección Virtual',
      namePlaceholder: 'Nombre de la colección',
      createBtn: 'Crear',
    },
    customFields: {
      title: 'Gestionar Campos Personalizados',
      activeFieldsLabel: 'Campos Activos',
      activeFieldsCount: 'Campos Activos ({count})',
      deleteFieldTooltip: 'Eliminar campo',
      createNewFieldLabel: 'Crear Nuevo Campo',
      fieldNameLabel: 'Nombre del Campo',
      fieldNamePlaceholder: 'Ej: Año de Composición, Editorial...',
      fieldTypeLabel: 'Tipo de Dato',
      fieldTypeOptions: {
        text: 'Texto',
        number: 'Número',
        select: 'Desplegable (Selección)',
        boolean: 'Verdadero / Falso',
      },
      optionsLabel: 'Opciones (separadas por coma)',
      optionsPlaceholder: 'Opción 1, Opción 2, Opción 3',
      closeBtn: 'Cerrar',
      saveFieldBtn: 'Guardar Campo',
    },
    editMetadata: {
      titlePrefix: 'Revisar Metadatos:',
      titleLabel: 'Título de la Obra',
      composerLabel: 'Compositor / Autor',
      tagsLabel: 'Etiquetas (#Tags)',
      customFieldsLabel: 'Campos Personalizados',
      cancelBtn: 'Cancelar',
      confirmBtn: 'Confirmar y Guardar Metadatos',
    },
  },
  upload: {
    dropzone: {
      sheetMusicIcon: '🎼',
      instruction: 'Arrastra tus partituras aquí o haz clic para explorar',
    },
    queue: {
      containerTitle: 'Cola de procesamiento y carga ({count})',
      containerIcon: '📥',
      uploadAllIcon: '🚀',
      fileIcon: '📄',
      pendingStatus: 'En espera',
      uploadSingleIcon: '⬆️',
      uploadSingleBtn: 'Subir',
      discardTooltip: 'Descartar',
      error: {
        icon: '⚠️',
        title: 'Error al procesar la partitura',
        defaultMessage: 'No se pudo leer el archivo o el PDF no contiene texto procesable.',
        discardBtn: 'Descartar',
      },
      metadataReview: {
        icon: '✨',
        title: 'Metadatos extraídos por IA/OCR',
        hint: 'Verifica antes de catalogar',
        titleLabel: 'Título de la Obra',
        titlePlaceholder: 'Título',
        composerLabel: 'Compositor / Autor',
        composerPlaceholder: 'Compositor',
        tagsLabel: 'Etiquetas (#Tags)',
        tagsPlaceholder: 'Añadir etiqueta y presionar Enter...',
        customFieldsLabel: 'Campos personalizados',
        confirmBtn: 'Confirmar y Añadir a Biblioteca',
      },
    },
  },
  tagInput: {
    placeholderEmpty: 'Escribe una etiqueta y pulsa Enter...',
    placeholderAdd: '+ Añadir...',
    tagPrefix: '#',
    existingLabel: 'Existente',
  },
  searchBar: {
    icon: '🔍',
    placeholder: 'Buscar por compositor, título, etiquetas o texto interno del PDF...',
    filtering: 'Filtrando...',
  },
  documentCard: {
    fileIcon: '📄',
    confirmedBadge: 'Confirmado',
    composerLabel: 'Compositor:',
    removeFromCollectionTooltip: 'Quitar de esta colección',
    removeFromCollectionBtn: '✕ Desasignar',
    viewPdfTooltip: 'Ver partitura en el visor integrado',
    viewPdfIcon: '👁️',
    viewPdfBtn: 'Ver PDF',
    editBtn: 'Editar',
    moveToOption: '📁 Mover a...',
  },
  pdfViewer: {
    sheetMusicIcon: '🎼',
    prevPageTitle: 'Página Anterior (←)',
    prevPageIcon: '◀',
    nextPageTitle: 'Página Siguiente (→)',
    nextPageIcon: '▶',
    pageSeparator: '/',
    zoomOut: '-',
    zoomIn: '+',
    fitWidthBtn: 'Ajustar Ancho',
    atrilIcon: '📖',
    atrilBtn: 'Modo Atril',
    atrilTitle: 'Activar Modo Atril (Pantalla completa)',
    closeBtn: '✕ Cerrar',
    exitAtrilBtn: '✕ Salir de Modo Atril',
    exitAtrilTitle: 'Salir de Modo Atril (Esc)',
    loadingText: 'Cargando partitura...',
    errorIcon: '⚠️',
    loadPdfErrorText: 'No se pudo cargar el archivo PDF.',
    loadPdfErrorLog: 'Error al cargar el PDF:',
    renderErrorLog: 'Error al renderizar página:',
  },
  facetedFilters: {
    titleIcon: '🎛️',
    title: 'Filtros Facetados',
    clearAllBtn: 'Limpiar todo',
    composersSection: 'Compositores / Autores',
    tagsSection: 'Etiquetas (#Tags)',
    customFieldsSection: 'Campos Personalizados',
    selectAllCustomField: 'Todos ({fieldName})',
    filterByCustomFieldPlaceholder: 'Filtrar por {fieldName}...',
  },
  home: {
    dropRejectedError: 'Formato no soportado en esta versión',
    rootLibraryTitle: 'Biblioteca Raíz',
    collectionTitlePrefix: 'Colección: ',
  },
} as const;