- name: JSON Replace
  # You may pin to the exact commit or the version.
  # uses: beards-and-binary/json-replace@15bf7389f6f350f44b69dc156c833071f3cf2c52
  uses: beards-and-binary/json-replace@v1.1
  with:
    # The JSON to update
    json: 
    # A list of properties to update in the JSON, passed as key, value sub-lists
    updates: 
